"""add refresh token fields to auth_accounts

Revision ID: 19d6f92b3121
Revises: 2987ddf097e5
Create Date: 2026-02-27 04:06:04.791009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d6f92b3121'
down_revision = '2987ddf097e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_accounts', sa.Column('refresh_token_hash', sa.String(length=255), nullable=True))
    op.add_column('auth_accounts', sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_accounts', 'refresh_token_expires_at')
    op.drop_column('auth_accounts', 'refresh_token_hash')
    # ### end Alembic commands ### 