"""add login lockout fields to auth_accounts

Revision ID: 2987ddf097e5
Revises: e55d123a262d
Create Date: 2026-02-27 03:36:34.952230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2987ddf097e5'
down_revision = 'e55d123a262d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_accounts', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('auth_accounts', sa.Column('login_locked_until', sa.DateTime(), nullable=True))
    op.alter_column('products', 'brand_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'brand_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('auth_accounts', 'login_locked_until')
    op.drop_column('auth_accounts', 'failed_login_attempts')
    # ### end Alembic commands ### 