"""Add available_sizes to Product model

Revision ID: 2f3g4h5i6j7k
Revises: 1e2f3g4h5i6j
Create Date: 2025-07-19 00:25:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f3g4h5i6j7k'
down_revision = '1e2f3g4h5i6j'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('available_sizes', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'available_sizes')
    # ### end Alembic commands ###
