"""add_password_history_to_user

Revision ID: 3a9fdf26bf84
Revises: 8cb23ed58f43
Create Date: 2025-09-09 15:24:03.983930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a9fdf26bf84'
down_revision = '8cb23ed58f43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_history', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_history')
    # ### end Alembic commands ### 