"""add official_name to brand

Revision ID: 3fe40ab00958
Revises: 5e27ff57677f
Create Date: 2026-03-25 18:59:53.788777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe40ab00958'
down_revision = '5e27ff57677f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('official_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'official_name')
    # ### end Alembic commands ### 