"""add brand_withdrawals table

Revision ID: 5b54233ce0f8
Revises: 19d6f92b3121
Create Date: 2026-02-27 04:49:28.395177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b54233ce0f8'
down_revision = '19d6f92b3121'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 