"""add brand legal fields remove payout_account_locked

Revision ID: 5e27ff57677f
Revises: afb8d15de082
Create Date: 2026-03-25 02:40:52.116914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e27ff57677f'
down_revision = 'afb8d15de082'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('contact_phone', sa.String(length=20), nullable=True))
    op.add_column('brands', sa.Column('tax_system', sa.String(length=10), nullable=True))
    op.add_column('brands', sa.Column('vat_payer', sa.Boolean(), nullable=True))
    op.add_column('brands', sa.Column('vat_rate', sa.String(length=5), nullable=True))
    op.add_column('brands', sa.Column('kpp', sa.String(length=9), nullable=True))
    op.add_column('brands', sa.Column('ogrn', sa.String(length=15), nullable=True))
    op.drop_column('brands', 'payout_account_locked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('payout_account_locked', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('brands', 'ogrn')
    op.drop_column('brands', 'kpp')
    op.drop_column('brands', 'vat_rate')
    op.drop_column('brands', 'vat_payer')
    op.drop_column('brands', 'tax_system')
    op.drop_column('brands', 'contact_phone')
    # ### end Alembic commands ### 