"""Manually add images column and remove image_url column

Revision ID: 61d2a063c042
Revises: e958afff08f1
Create Date: 2025-08-04 22:56:31.978334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '61d2a063c042'
down_revision = 'e958afff08f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('images', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(length=500), autoincrement=False, nullable=True))
    op.drop_column('products', 'images')
    # ### end Alembic commands ###