"""add sale price and sizing table to products

Revision ID: 7895696e1a95
Revises: a22c8097538a
Create Date: 2026-02-24 01:21:42.760250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7895696e1a95'
down_revision = 'a22c8097538a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sale_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('sale_type', sa.String(length=10), nullable=True))
    op.add_column('products', sa.Column('sizing_table_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'sizing_table_image')
    op.drop_column('products', 'sale_type')
    op.drop_column('products', 'sale_price')
    # ### end Alembic commands ### 