"""Add email verification code

Revision ID: 8cb23ed58f43
Revises: f51d90486a01
Create Date: 2025-09-07 20:49:46.115272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8cb23ed58f43'
down_revision = 'f51d90486a01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verification_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('email_verification_code_expires_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'verification_token_expires')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'is_onboarded')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_onboarded', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('verification_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('verification_token_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'email_verification_code_expires_at')
    op.drop_column('users', 'email_verification_code')
    # ### end Alembic commands ### 