"""add indexes on FK columns

Revision ID: 8ec0eb19b593
Revises: 5b54233ce0f8
Create Date: 2026-02-27 20:59:31.805740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec0eb19b593'
down_revision = '5b54233ce0f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_checkouts_user_id'), 'checkouts', ['user_id'], unique=False)
    op.create_index(op.f('ix_friend_requests_recipient_id'), 'friend_requests', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_friend_requests_sender_id'), 'friend_requests', ['sender_id'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_user_id'), 'oauth_accounts', ['user_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_variant_id'), 'order_items', ['product_variant_id'], unique=False)
    op.create_index(op.f('ix_orders_brand_id'), 'orders', ['brand_id'], unique=False)
    op.create_index(op.f('ix_orders_checkout_id'), 'orders', ['checkout_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_product_color_variants_product_id'), 'product_color_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_product_color_variant_id'), 'product_variants', ['product_color_variant_id'], unique=False)
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_user_brands_brand_id'), 'user_brands', ['brand_id'], unique=False)
    op.create_index(op.f('ix_user_brands_user_id'), 'user_brands', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_liked_products_product_id'), 'user_liked_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_user_liked_products_user_id'), 'user_liked_products', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_styles_style_id'), 'user_styles', ['style_id'], unique=False)
    op.create_index(op.f('ix_user_styles_user_id'), 'user_styles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_styles_user_id'), table_name='user_styles')
    op.drop_index(op.f('ix_user_styles_style_id'), table_name='user_styles')
    op.drop_index(op.f('ix_user_liked_products_user_id'), table_name='user_liked_products')
    op.drop_index(op.f('ix_user_liked_products_product_id'), table_name='user_liked_products')
    op.drop_index(op.f('ix_user_brands_user_id'), table_name='user_brands')
    op.drop_index(op.f('ix_user_brands_brand_id'), table_name='user_brands')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_index(op.f('ix_product_variants_product_color_variant_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_color_variants_product_id'), table_name='product_color_variants')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_checkout_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_brand_id'), table_name='orders')
    op.drop_index(op.f('ix_order_items_product_variant_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_oauth_accounts_user_id'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_friend_requests_sender_id'), table_name='friend_requests')
    op.drop_index(op.f('ix_friend_requests_recipient_id'), table_name='friend_requests')
    op.drop_index(op.f('ix_checkouts_user_id'), table_name='checkouts')
    # ### end Alembic commands ### 