"""add amount_withdrawn to brand

Revision ID: 978fbe4aff1b
Revises: dfd1d514f152
Create Date: 2025-09-05 15:24:32.227644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978fbe4aff1b'
down_revision = 'dfd1d514f152'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('amount_withdrawn', sa.Float(), nullable=True))
    op.execute("UPDATE brands SET amount_withdrawn = 0.0 WHERE amount_withdrawn IS NULL")
    op.alter_column('brands', 'amount_withdrawn', existing_type=sa.Float(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'amount_withdrawn') 