"""add delivery time to brands and products

Revision ID: a22c8097538a
Revises: 04_order_status_foundation
Create Date: 2026-02-23 21:04:25.251649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = 'a22c8097538a'
down_revision = '04_order_status_foundation'
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    brand_cols = [c['name'] for c in inspector.get_columns('brands')]
    product_cols = [c['name'] for c in inspector.get_columns('products')]
    if 'delivery_time_min' not in brand_cols:
        op.add_column('brands', sa.Column('delivery_time_min', sa.Integer(), nullable=True))
    if 'delivery_time_max' not in brand_cols:
        op.add_column('brands', sa.Column('delivery_time_max', sa.Integer(), nullable=True))
    if 'delivery_time_min' not in product_cols:
        op.add_column('products', sa.Column('delivery_time_min', sa.Integer(), nullable=True))
    if 'delivery_time_max' not in product_cols:
        op.add_column('products', sa.Column('delivery_time_max', sa.Integer(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'delivery_time_max')
    op.drop_column('products', 'delivery_time_min')
    op.drop_column('brands', 'delivery_time_max')
    op.drop_column('brands', 'delivery_time_min')
    # ### end Alembic commands ### 