"""Add email verification and password reset fields to Brand model

Revision ID: c8cc04d6469c
Revises: f6531bca9ba9
Create Date: 2025-10-06 14:03:17.912981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8cc04d6469c'
down_revision = 'f6531bca9ba9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 