"""Remove honest_sign

Revision ID: e2b7b23c6d57
Revises: eaaa7612bbe2
Create Date: 2025-09-06 02:26:18.616219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b7b23c6d57'
down_revision = 'eaaa7612bbe2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_honest_sign_key', 'products', type_='unique')
    op.drop_column('products', 'honest_sign')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('honest_sign', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint('products_honest_sign_key', 'products', ['honest_sign'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ### 