"""Remove return_policy

Revision ID: eaaa7612bbe2
Revises: 978fbe4aff1b
Create Date: 2025-09-06 02:24:47.222955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaaa7612bbe2'
down_revision = '978fbe4aff1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'return_policy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('return_policy', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ### 