"""Change price columns to Float

Revision ID: f51d90486a01
Revises: e2b7b23c6d57
Create Date: 2025-09-06 03:17:51.562080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f51d90486a01'
down_revision = 'e2b7b23c6d57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brands', 'shipping_price',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using="regexp_replace(shipping_price, E'[^0-9.]+', '', 'g')::double precision")
    op.alter_column('order_items', 'price',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=False,
               postgresql_using="regexp_replace(price, E'[^0-9.]+', '', 'g')::double precision")
    op.alter_column('orders', 'total_amount',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=False,
               postgresql_using="regexp_replace(total_amount, E'[^0-9.]+', '', 'g')::double precision")
    op.alter_column('payments', 'amount',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=False,
               postgresql_using="regexp_replace(amount, E'[^0-9.]+', '', 'g')::double precision")
    op.alter_column('products', 'price',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=False,
               postgresql_using="regexp_replace(price, E'[^0-9.]+', '', 'g')::double precision")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using='price::varchar')
    op.alter_column('payments', 'amount',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using='amount::varchar')
    op.alter_column('orders', 'total_amount',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using='total_amount::varchar')
    op.alter_column('order_items', 'price',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using='price::varchar')
    op.alter_column('brands', 'shipping_price',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               postgresql_using='shipping_price::varchar')
    # ### end Alembic commands ###
