"""Initial migration from current models

Revision ID: f6531bca9ba9
Revises: 
Create Date: 2025-09-19 00:25:52.010128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6531bca9ba9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create all tables from models
    from database import init_db
    init_db()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop all tables from models
    from database import drop_db
    drop_db()
    # ### end Alembic commands ### 