"""Add description, brand_id, and style_id to Product model

Revision ID: fd48051c7047
Revises: f1a2b3c4d5e6
Create Date: 2025-07-15 00:07:33.911764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd48051c7047'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('products', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('style_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'])
    op.create_foreign_key(None, 'products', 'styles', ['style_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'style_id')
    op.drop_column('products', 'brand_id')
    op.drop_column('products', 'description')
    # ### end Alembic commands ###